import { Definicion } from "../modelo/Definicion";

export const VOCABULARIO: Definicion[] = [
  { tipo: 'otros', texto: 'je/jouw', traduccion: 'tú/tu' },
  { tipo: 'sustantivo', texto: 'guld/gulden', traduccion: 'moneda/monedas' },
  { tipo: 'verbo', texto: 'trek X kaarten', traduccion: 'roba X cartas' },
  { tipo: 'verbo', texto: 'leg X kaarten', traduccion: 'Deja X cartas' },
  { tipo: 'verbo', texto: 'voeg (...) toe aan je hand', traduccion: 'añade (...) a tu mano' },
  { tipo: 'verbo', texto: 'ontvang', traduccion: 'recibe' },
  { tipo: 'verbo', texto: 'hebt', traduccion: 'tienes' },
  { tipo: 'expresión', texto: 'als je (...) hebt', traduccion: 'si tienes (...)' },
  { tipo: 'verbo', texto: 'speel X kaarten', traduccion: 'juega X cartas' },
  { tipo: 'verbo', texto: 'omruilen', traduccion: 'cambiar' },
  { tipo: 'expresión', texto: 'de actie X uitvoeren', traduccion: 'realizar la acción X' },
  { tipo: 'expresión', texto: 'volledig hebt gebouwd', traduccion: 'tengas completamente construido' },
  { tipo: 'verbo', texto: 'geef', traduccion: 'da' },
  { tipo: 'verbo', texto: 'aflegen', traduccion: 'descartar' },
  { tipo: 'verbo', texto: 'betaal', traduccion: 'paga' },
  { tipo: 'verbo', texto: 'vooruitgaan', traduccion: 'progresar' },
  { tipo: 'verbo', texto: 'kiest', traduccion: 'elijas' },
  { tipo: 'verbo', texto: 'nemen', traduccion: 'tomar/coger' },
  { tipo: 'verbo', texto: 'krijgen', traduccion: 'recibir' },
  { tipo: 'verbo', texto: 'aantrekt', traduccion: 'atraer (se refiere a meter personas en casas)' },
  { tipo: 'expresión', texto: 'neemt men terug', traduccion: 'retornar/volver' },
  { tipo: 'expresión', texto: 'telt aan', traduccion: 'cuenta como' },
  { tipo: 'expresión', texto: 'elke keer als', traduccion: 'cada vez que' },
  { tipo: 'sustantivo', texto: 'arbeider', traduccion: 'trabajador' },
  { tipo: 'expresión', texto: 'voor elke', traduccion: 'por cada' },
  { tipo: 'sustantivo', texto: 'speelgebied', traduccion: 'área de juego' },
  { tipo: 'otros', texto: 'als', traduccion: 'si (condicional)' },
  { tipo: 'expresión', texto: 'het einde van het spel', traduccion: 'el final de la partida' },
  { tipo: 'sustantivo', texto: 'kleur/kleuren', traduccion: 'color/colores' },
  { tipo: 'expresión', texto: 'verschillende kleuren', traduccion: 'diferentes colores' },
  { tipo: 'expresión', texto: 'naar keuze', traduccion: 'a elegir' },
  { tipo: 'expresión', texto: 'een aantal', traduccion: 'cualquier cantidad' },
  { tipo: 'expresión', texto: 'eenmal per ronde', traduccion: 'una vez por ronda' },
  { tipo: 'sustantivo', texto: 'bevolkingsgroep', traduccion: 'grupo de población' },
  { tipo: 'expresión', texto: 'andere kleuren', traduccion: 'otros colores' },
  { tipo: 'expresión', texto: 'zonder daarvoor geld te betalen', traduccion: 'sin pagar dinero' },
  { tipo: 'expresión', texto: 'de kaart is wel nodig', traduccion: 'la carta es necesaria' },
  { tipo: 'otros', texto: 'derde', traduccion: 'tercera (3ª)' },
  { tipo: 'otros', texto: 'vierde', traduccion: 'cuarta (4ª)' },
  { tipo: 'expresión', texto: 'X gulden minder', traduccion: 'X monedas menos' },
  { tipo: 'sustantivo', texto: 'stap', traduccion: 'paso/casilla/posición' },
  { tipo: 'sustantivo', texto: 'veld', traduccion: 'casilla/posición' },
  { tipo: 'otros', texto: 'altijd', traduccion: 'siempre' },
  { tipo: 'otros', texto: 'minstens', traduccion: 'al menos' },
  { tipo: 'expresión', texto: 'ook als normaal vooruitgaan niet mogelijk is', traduccion: 'incluso si no es posible el progreso de forma normal' },
  { tipo: 'expresión', texto: 'dezelfde kleur', traduccion: 'mismo color' },
  { tipo: 'expresión', texto: 'vanaf nu', traduccion: 'a partir de ahora' },
  { tipo: 'sustantivo', texto: 'standbeel-fiches', traduccion: 'fichas de estatua' },
  { tipo: 'sustantivo', texto: 'meerder-heids-fiche', traduccion: 'ficha de mayoría' },
  { tipo: 'sustantivo', texto: 'noodlot', traduccion: 'maldición' },
  { tipo: 'otros', texto: 'Rechter', traduccion: 'La habilidad de este personaje es que al determinar mayorías te sirve el empate' }
];
